---
# Collect SSH Known Host Keys Everywhere.  This is a "one time" operation
# but should be run everytime there's a new node added or rebuilt

- name: Collect SSH Keys for the target hosts
  hosts: management,k8s_cluster
  gather_facts: false
  connection: local

  vars:
    ansible_python_interpreter: python3
    known_hosts: "~/.ssh/known_hosts"

  tasks:
    - name: Run SSH Keyscan
      ansible.builtin.command: ssh-keyscan {{ ansible_host | default(inventory_hostname) }}
      register: "host_keys"
      changed_when: false

    - name: "Ensure workstation known hosts file exists"
      ansible.builtin.file:
        path: "{{ known_hosts }}"
        state: file
        mode: '0600'

    - name: "Add known host blocks to workstation known hosts"
      ansible.builtin.blockinfile:
        dest: "{{ known_hosts }}"
        marker: "# {mark} This part managed by Ansible"
        block: |
          {% for h in groups['all'] if hostvars[h].host_keys is defined %}
          {{ hostvars[h].host_keys.stdout }}
          {% endfor %}

# Generate an SSH key pair for easy login between nodes
- name: Generate SSH key for cluster login
  hosts: management
  gather_facts: false
  connection: local

  vars:
    ansible_python_interpreter: python3

  tasks:
    - name: Validate key existence
      ansible.builtin.stat:
        path: "{{ key_filename }}"
      register: cluster_ssh_key

    - name: Generate key
      ansible.builtin.command: ssh-keygen -q -f {{ key_filename }} -N ''
      when: cluster_ssh_key.stat.exists is false

- name: Apply the common role
  hosts: management,k8s_cluster

  roles:
    - common

  tasks:
    - name: "Ensure root SSH configuration exists"
      ansible.builtin.file:
        path: /root/.ssh
        mode: '0700'
        state: directory

    - name: "Copy authorized key to each node"
      ansible.builtin.copy:
        src: "{{ key_filename }}.pub"
        dest: /root/.ssh/authorized_keys
        mode: '0644'
        owner: root
        group: root

    - name: "Copy private key to each node"
      ansible.builtin.copy:
        src: "{{ key_filename }}"
        dest: "/root/.ssh/id_ed25519"
        mode: '0600'
        owner: root
        group: root
